package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/lollm/lollm/internal/auth"
	"github.com/lollm/lollm/internal/config"
	"github.com/lollm/lollm/internal/db"
	"github.com/lollm/lollm/internal/secret"
)

var setupKeyName string

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Initialize config.yaml, SQLite database, master key, and the first API key",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := context.Background()

		// 1) Config file — create with defaults if missing.
		cfgPath := configPath()
		if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
			if err := writeDefaultConfig(cfgPath); err != nil {
				return fmt.Errorf("write config: %w", err)
			}
			fmt.Printf("✔ config file created: %s\n", cfgPath)
		} else {
			fmt.Printf("• config file exists: %s\n", cfgPath)
		}

		// 2) Effective config (now that the file exists).
		cfg, err := loadConfig(config.FlagOverrides{})
		if err != nil {
			return err
		}

		// 3) Master key — lives next to the database (or $LOLLM_MASTER_KEY).
		masterKeyPath := secret.MasterKeyPath(filepath.Dir(cfg.DBPath))
		masterKey, err := secret.LoadOrCreateMasterKey(masterKeyPath)
		if err != nil {
			return fmt.Errorf("master key: %w", err)
		}
		fmt.Printf("✔ master key ready: %s\n", masterKeyPath)

		// 4) Database: migrate schema + seed demo data.
		store, err := openStore(cfg)
		if err != nil {
			return fmt.Errorf("database: %w", err)
		}
		defer store.Close()
		if err := db.SeedIfEmpty(ctx, store, masterKey); err != nil {
			return fmt.Errorf("seed: %w", err)
		}
		fmt.Printf("✔ database ready: %s (schema migrated, demo data seeded)\n", cfg.DBPath)

		// 5) First internal API key (used by coding tools as the API key).
		nActive, err := store.CountActiveAPIKeys(ctx)
		if err != nil {
			return err
		}
		if nActive == 0 {
			plain, err := auth.GenerateAPIKey()
			if err != nil {
				return err
			}
			k := &db.APIKey{
				Name:      setupKeyName,
				KeyHash:   auth.HashKey(plain),
				KeyPrefix: auth.DisplayPrefix(plain),
				IsActive:  true,
			}
			if err := store.CreateAPIKey(ctx, k); err != nil {
				return err
			}
			fmt.Println("✔ internal API key created (shown ONCE — store it now):")
			fmt.Printf("    %s\n", plain)
			fmt.Printf("    (id: %s)\n", k.ID)
		} else {
			fmt.Printf("• %d active internal API key(s) exist — create more with `lollm key generate`\n", nActive)
		}

		// 6) Dashboard password (default seeded automatically on first use).
		fmt.Println("✔ dashboard password aktif — default: edoll123 (ubah di Settings → Password Dashboard)")

		fmt.Println()
		fmt.Println("Next steps:")
		fmt.Printf("  1. ./bin/lollm serve      # API on :%d, dashboard on :%d (phase P4)\n", cfg.APIPort, cfg.DashboardPort)
		fmt.Printf("  2. Point your tools at http://localhost:%d/v1 using the API key above\n", cfg.APIPort)
		fmt.Println("  3. Replace demo connections with real provider keys via the dashboard")
		return nil
	},
}

// writeDefaultConfig writes a fresh, commented config.yaml.
func writeDefaultConfig(path string) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	out, err := config.Default().YAML()
	if err != nil {
		return err
	}
	header := `# LoLLM configuration (generated by 'lollm setup')
# Precedence: CLI flags > env vars (HOST, API_PORT, ...) > this file > defaults

`
	return os.WriteFile(path, []byte(header+out), 0o644)
}

func init() {
	setupCmd.Flags().StringVar(&setupKeyName, "key-name", "default", "name for the first internal API key")
	rootCmd.AddCommand(setupCmd)
}
